version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7

    # Group packages into shared PR
    groups:
      weekly-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'
    schedule:
      interval: weekly
      day: monday

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
