name: Check Pull Request

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: write

jobs:
  validate-pr:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org/"
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Scan security vulnerabilities
        run: npm audit --audit-level=high --omit dev

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run prettier

      - name: Test
        if: ${{ !startsWith(github.head_ref, 'changeset-release/') }}
        run: npm test

      - name: SonarCloud Scan
        if: github.actor != 'dependabot[bot]' &&
          !startsWith(github.head_ref, 'changeset-release/')
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f #8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
